on: push

jobs:
  build-opm:
    container:
      image: freicon/opmbuild
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Check SOPM
      run: /usr/local/bin/opmbuild sopmtest $GITHUB_WORKSPACE/SuperAdmin.sopm
    - name: build OPM
      run: /usr/local/bin/opmbuild build $GITHUB_WORKSPACE/SuperAdmin.sopm
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: SuperAdmin
        path: ${{ github.workspace }}/*.opm
        retention-days: 7
